# Site settings
url: "http://majapasovic.org"
title: "Maja Pašović"
description: "The Writings of Maja Pašović"
author: "Maja Pašović"
email: "maja@majapasovic.org"
github: "mpasovic"

# Conversion
markdown: kramdown

# Outputting
permalink: none

prose:
  siteurl: "http://majapasovic.org"
  media: "img"
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /fonts
    - /js
    - /.gitignore
    - /CNAME
    - /feed.xml
    - /robots.txt
    - /journal.html
    - /favicon.png
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "the great title"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
